#!/bin/bash

for run in {1..30}
do
    echo "Iteration: $run"

    python train.py \
            --dataset film \
            --checkpt_file pre_trained/film/film_mod.ckpt \
            --train_size 50 \
            --validation_size 500 \
            --dropout 0.6 \
            --seed $run \
	    >> rnnets_gru_accuracy_film_50.txt
done

python calculate_average_accuracy.py \
        --file_name rnnets_gru_accuracy_film_50.txt \
